name: 'Backend: Check the source code'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i
        working-directory: ./server
      - name: Run prettier
        run: npm run format
        working-directory: ./server
      - name: Run eslint
        run: npm run lint
        working-directory: ./server
      - name: Run build
        run: npm run build
        working-directory: ./server
